name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CDK_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CDK dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/cdk/requirements.txt

      - name: CDK Diff
        run: |
          cd deploy/cdk
          cdk diff --context githubOrg=${{ vars.GITHUB_ORG }} --context githubRepo=${{ vars.GITHUB_REPO }}

      - name: CDK Deploy
        run: |
          cd deploy/cdk
          cdk deploy --require-approval never \
            --context githubOrg=${{ vars.GITHUB_ORG }} \
            --context githubRepo=${{ vars.GITHUB_REPO }}

